const jwt = require("jsonwebtoken");
require("dotenv/config")

/**
 *
 * @param userId: the id of the user
 * @returns {Promise<*|null>} returns a token generated by the jwt algorithm. If it fails to generate it, null is returned
 */
const generateToken = async (userId) => {
    try {
        const token = await jwt.sign({userId}, process.env.SECRET_KEY, {expiresIn: '30m'});
        return token;
    } catch (error) {
        return null;
    }
}


module.exports = generateToken;